name: Laravel

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: "testing"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env.example .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Composer update
      run: composer update
    - name: Install NPM Dependencies
      run: |
        npm install
        npm run build
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Spatie Permissions
      run: |
        php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"
        php artisan optimize:clear
    - name: Database population
      run: |
        php artisan config:cache
        php artisan migrate
        php artisan migrate --path=/vendor/spatie/laravel-permission/database/migrations
        php artisan db:seed
      env:
        DB_DATABASE: testing
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit